import { Amplify } from 'aws-amplify';
import { generateClient } from 'aws-amplify/data';
import type { Schema } from '../../amplify/data/resource';
import outputs from '../../amplify_outputs.json';

Amplify.configure(outputs);

/** Reads public content as a visitor (identity pool, guest or signed-in). */
export const publicClient = generateClient<Schema>({ authMode: 'identityPool' });
/** Acts as the signed-in user (student or staff). */
export const userClient = generateClient<Schema>({ authMode: 'userPool' });

export type { Schema };
export type ModelName = keyof typeof userClient.models;

export type Member = Schema['Member']['type'];
export type MemberProfile = Schema['MemberProfile']['type'];
export type Post = Schema['Post']['type'];
export type Publication = Schema['Publication']['type'];
export type Project = Schema['Project']['type'];
export type Award = Schema['Award']['type'];
export type Album = Schema['Album']['type'];
export type Guest = Schema['Guest']['type'];
export type SiteContent = Schema['SiteContent']['type'];
export type Submission = Schema['Submission']['type'];
export type AuditLog = Schema['AuditLog']['type'];
export type VisitStat = Schema['VisitStat']['type'];

/** True when amplify_outputs.json has been generated by a real deployment. */
export const isConfigured = Boolean((outputs as { data?: unknown }).data);

type ListResult = { data: unknown[]; nextToken?: string | null; errors?: { message: string }[] };

/** Fetches every item of a model, following pagination. */
export async function listAll<T>(model: unknown, extra: Record<string, unknown> = {}): Promise<T[]> {
  const m = model as { list: (o: Record<string, unknown>) => Promise<ListResult> };
  const items: T[] = [];
  let nextToken: string | null | undefined;
  do {
    const res = await m.list({ limit: 1000, nextToken, ...extra });
    if (res.errors?.length) throw new Error(res.errors.map((e) => e.message).join('; '));
    items.push(...(res.data.filter(Boolean) as T[]));
    nextToken = res.nextToken;
  } while (nextToken);
  return items;
}

/** Throws the first GraphQL error of a mutation result, otherwise returns its data. */
export function unwrap<T>(res: { data?: T | null; errors?: { message: string }[] }): T {
  if (res.errors?.length) throw new Error(res.errors.map((e) => e.message).join('; '));
  return res.data as T;
}

/** Parses a.json() fields, which arrive either as objects or as JSON strings. */
export function parseJson<T>(value: unknown, fallback: T): T {
  if (value == null || value === '') return fallback;
  if (typeof value === 'string') {
    try {
      return JSON.parse(value) as T;
    } catch {
      return fallback;
    }
  }
  return value as T;
}
